camera:
    depth:
        image_rect_raw:
            image_transport: "raw"
    aligned_depth_to_color:
        image_raw:
            compressed:
                format: "png"
                png_level: 5
    color:
        image_raw:
            compressed:
                format: "jpeg"
                jpeg_quality: 75

